### ISSUE TITLE
data collecting

### ISSUE THREAD

**Issue by jacer0** [deepaktalwardt/lgsvl_micromobility_ros_pkgs#1]
the launch file worrk without errors, 
i created a folder dataset in my work space, remplaced the path name "folder = "/home/adas/Bureau/catkin_ws/dataset" " in data_collector_nodepy but i di not recieve any information, the folder still empty after executing the launch file and driving appollo car manually with enabling lidar and camera sensors

**Comment by deepaktalwardt** [comment]
Did you launch rosbridge? You will need to have rosbridge running in a separate terminal that facilitates the communication between the simulator and ROS. 

Once you have rosbridge working, "Connected" will appear in the top left corner in the simulator. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacer0** [comment]
yes i launched ros bridge 
![Screenshot from 2019-06-10 21-25-08](https://user-images.githubusercontent.com/51677844/59220985-86a11580-8bc6-11e9-892a-dae2808c9fa9.png)
![Screenshot from 2019-06-10 21-26-23](https://user-images.githubusercontent.com/51677844/59220986-8739ac00-8bc6-11e9-859a-6a685930d15a.png)
But it shows the following error 
"[ERROR] [1560194793.049019]: [Client 32] advertise: Unable to load the manifest for package lgsvl_msgs. Caused by: lgsvl_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
[ERROR] [1560194793.051624]: [Client 32] advertise: Unable to load the manifest for package lgsvl_msgs. Caused by: lgsvl_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
[ERROR] [1560194793.054678]: [Client 32] advertise: Unable to load the manifest for package pb_msgs. Caused by: pb_msgs
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
[ERROR] [1560194793.056616]: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 63, in wrapper
    return f(*args, **kwargs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 142, in on_message
    self.protocol.incoming(message)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosbridge_library/protocol.py", line 120, in incoming
    self.buffer = self.buffer + message_string
TypeError: must be str, not bytes
"

**Comment by deepaktalwardt** [comment]
It looks like the issue might be in lgsvl_msgs. Can you see if you can find it from the terminal? You can try `rospack find lgsvl_msgs`

If you can't find it, it's probably because it's not in your path. Also, I see that you're using melodic. I tested this code on Kinetic, so I'm not sure if that can cause any issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacer0** [comment]
I found it when in the repository
![Screenshot from 2019-06-10 21-40-16](https://user-images.githubusercontent.com/51677844/59221797-5eb2b180-8bc8-11e9-8df2-0fd196bd86f9.png)
But in an other terminal i couldn't you are right
![Screenshot from 2019-06-10 21-43-55](https://user-images.githubusercontent.com/51677844/59222088-fc0de580-8bc8-11e9-8726-0b94aa20c0a2.png)
How can i solve it ?

**Comment by deepaktalwardt** [comment]
You should check if you have your workspace in the ROS_PACKAGE_PATH. You might need to modify the path to find these packages. You can follow the instructions here http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment.

Also, sourcing of setup.bash didn't work in your second screenshot. That can also be a problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
